### ISSUE TITLE
CRAN message about broken reverse dependency checks

### ISSUE THREAD

**Issue by jsta** [ropensci/vcr#235] opened 2021-05-24 14:43 UTC
> Subject: CRAN packages archiveRetriever dbhydroR deepdep hlidacr intensegRid weathercan
Today's vcr update 1.0.0 has broken the checks of these.

All tests pass locally for me (running `devtools::test`) but fail running as part of `devtools::check`. The error I get is the same as CRAN:

> Error: No root directory found in /home/hornik/tmp/R.check/r-devel-gcc/Work/PKGS/dbhydroR.Rcheck/tests/testthat or its parent directories. Root criterion: contains a file "DESCRIPTION" with contents matching "^Package: "

I was able to pass check associated tests by removing the call to `vcr_test_path` in the autogenerated "setup" file and hardcoding the path to the fixtures directory.

**Comment by jsta** [comment] 2021-05-24 14:54
`dir = vcr::vcr_test_path("fixtures")` -> `dir = "../fixtures"`

**Comment by sckott** [comment] 2021-05-24 15:33
Thanks. Was going to send an email to people this morning. I did run revdep checks and didn't get any issues (and I don't personally use the function in my own http pkgs), but I should have emailed about this issue, sorry about that. Looking into it

**Comment by dpprdan** [comment] 2021-05-24 17:10
👋🏻 My PR #230 probably caused this. Sorry for the trouble this is causing!

I can reproduce with https://github.com/ropensci/opencage/tree/devel. `devtools::check()`/R CMD check apparently moves the test dir outside the pkg dir: 

```
.
+-- 00check.log
+-- 00install.out
+-- 00_pkg_src
|   \-- opencage
+-- opencage
|   +-- data
|   +-- DESCRIPTION
|   +-- doc
|   +-- extdata
|   +-- help
|   +-- html
|   +-- INDEX
|   +-- Meta
|   +-- NAMESPACE
|   +-- NEWS.md
|   \-- R
+-- opencage-Ex.pdf
+-- opencage-Ex.R
+-- opencage-Ex.Rout
+-- opencage-Ex.timings
\-- tests
    +-- startup.Rs
    +-- testthat
    +-- testthat.R
    +-- testthat.Rout.fail
    \-- vcr_cassettes
```

(`vcr_cassettes` is what is usually called `fixtures`)

I looking into ways how to catch this. Maybe `rprojroot::has_dir("tests")`?

**Comment by dpprdan** [comment] 2021-05-24 17:51
[Using `rprojroot::has_dir("tests")`](https://github.com/dpprdan/vcr/blob/2881b588fe3eabac2c7a371f199aaad407b7bddf/R/vcr_test_path.R#L19) in `vcr_test_path()` seems to work in general, i.e. both `devtools::test()` and `devtools::check()` run successfully with this change on https://github.com/ropensci/opencage/tree/devel.

However, since `has_dir()` is starting to look up the `tests` dir from `./tests/testthat/`, it will use `./tests/testthat/tests/` or `./tests/tests/` as a "root" dir should those exist. The tests still run, though.

**Comment by sckott** [comment] 2021-05-24 18:00
@dpprdan  Thanks for the quick response

@jsta can you try again after installing the change @dpprdan made above `remotes::install_github("dpprdan/vcr@2881b588fe3eabac2c7a371f199aaad407b7bddf")`

**Comment by sckott** [comment] 2021-05-24 18:01
(p.s. @dpprdan ultimately responsibility is with me as the lead maintainer, so no worries)

**Comment by dpprdan** [comment] 2021-05-24 18:06
Thanks! Still sucks though to have this go to CRAN and causing revdeps to fail. Apparently I didn't run R CMD check on opencage since #230 got merged (or I didn't install that change locally?) or else I would have caught it. Strange.

**Comment by jsta** [comment] 2021-05-24 18:19
That fork breaks both tests and check-tests for me with the following errors respectively:

```
Testing dbhydroR
Error in vcr_c[[names(params)[i]]] <- params[[i]] : 
  wrong args for environment subassignment
```

```
 Error in vcr_c[[names(params)[i]]] <- params[[i]] : 
       wrong args for environment subassignment
     Calls: test_check ... source_dir -> lapply -> FUN -> eval -> eval -> <Anonymous>
     Execution halted
```

**Comment by jsta** [comment] 2021-05-24 18:20
Works with that fork!

**Closed** 2021-05-31 13:43 UTC
Labels: bug
