### ISSUE TITLE
GHA failures

### ISSUE THREAD

**Issue by maelle** [ropensci/vcr#241] opened 2021-12-13 07:58 UTC
Not sure why yet

**Comment by sckott** [comment] 2021-12-13 20:47
@maelle  is this superseded by #242 ?

**Comment by maelle** [comment] 2021-12-14 07:17
Not sure whether the failures are linked

**Comment by sckott** [comment] 2021-12-14 14:51
can you link to any of these failing

**Comment by maelle** [comment] 2021-12-14 15:19
https://github.com/ropensci/vcr/runs/4070341398?check_suite_focus=true

**Comment by sckott** [comment] 2021-12-14 18:53
Thanks. Oh, i thought you were talking about errors caused by vcr in other repos.

**Comment by sckott** [comment] 2021-12-17 16:30
fixed now

**Closed by sckott** 2021-12-17 16:30 UTC

**Comment by maelle** [comment] 2021-12-17 17:15
thanks a ton!
